[tox]
envlist = stage1, stage2, stage3

[testenv]
basepython = python3.11
deps =
    pytest

[testenv:stage1]
allowlist_externals = cmake
deps = nanobind
changedir = {toxinidir}/build_tox
commands =
    cmake ..
    cmake --build .

[testenv:stage2]
allowlist_externals = git
changedir = {toxinidir}/tests/ext/icon4py
commands =
    git submodule update --init --recursive
    pip install -r base-requirements-dev.txt
    pip install model/common'[netcfd]'

[testenv:stage3]
deps =
    numpy
allowlist_externals =
    pytest
changedir =
    {toxinidir}/tests
setenv =
    PYTHONPATH={env:PYTHONPATH}:{toxinidir}/build_tox:{toxinidir}/{[testenv:stage2]envsitepackagesdir}
commands =
    pytest -v -s test_nabla4_unstructured.py
